spring.application.name=portafolio
<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://ep-orange-breeze-ac1a44t2-pooler.sa-east-1.aws.neon.tech/portafolio?&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_wAI96JVSmBeG

spring.datasource.hikari.maximun-pool-size=10
spring.datasource.hikari.connection-timeout=20000

spring.sql.init.mode=always

file.upload.dir=src/main/resources/static/img/projects/

spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/
=======
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:10}
spring.datasource.hikari.connection-timeout=20000

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}

file.upload.dir=${FILE_UPLOAD_DIR:src/main/resources/static/img/projects/}

spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/,file:${STATIC_FILES_DIR:src/main/resources/static/}
>>>>>>> 3b90af7 (Actualizacion portafolio y preparado para despliegue)
